export const SET_CURRENT_RANDOM_KANA = 'SET_CURRENT_RANDOM_KANA'
export const USER_HAS_ANSWERED = 'USER_HAS_ANSWERED'
export const RESET_ANSWER_STATE = 'RESET_ANSWER_STATE'
export const USER_ANSWERED_CORRECTLY = 'USER_ANSWERED_CORRECTLY'
export const USER_ANSWERED_INCORRECTLY = 'USER_ANSWERED_INCORRECTLY'

export const INCREMENT_KANA_SHOWN_COUNT = 'INCREMENT_KANA_SHOWN_COUNT'
export const INCREMENT_KANA_SKIPPED_COUNT = 'INCREMENT_KANA_SKIPPED_COUNT'
export const INCREMENT_KANA_SUCCESS_COUNT = 'INCREMENT_KANA_SUCCESS_COUNT'
export const INCREMENT_KANA_FAILURE_COUNT = 'INCREMENT_KANA_FAILURE_COUNT'
export const DECREMENT_KANA_SKIPPED_COUNT = 'DECREMENT_KANA_SKIPPED_COUNT'

export const UPDATE_UNANSWERED_EXIT_MESSAGE_OPTION = 'UPDATE_UNANSWERED_EXIT_MESSAGE_OPTION'
export const UPDATE_ACTIVE_KANA_TYPES_OPTION = 'UPDATE_ACTIVE_KANA_TYPES_OPTION'
