export const SET_CURRENT_RANDOM_KANA = 'SET_CURRENT_RANDOM_KANA'
export const USER_HAS_ANSWERED = 'USER_HAS_ANSWERED'

export const INCREMENT_KANA_SHOWN_COUNT = 'INCREMENT_KANA_SHOWN_COUNT'
export const INCREMENT_KANA_SKIPPED_COUNT = 'INCREMENT_KANA_SKIPPED_COUNT'
export const INCREMENT_KANA_SUCCESS_COUNT = 'INCREMENT_KANA_SUCCESS_COUNT'
export const INCREMENT_KANA_FAILURE_COUNT = 'INCREMENT_KANA_FAILURE_COUNT'
export const DECREMENT_KANA_SKIPPED_COUNT = 'DECREMENT_KANA_SKIPPED_COUNT'
